### ISSUE TITLE
Supported Miners

### ISSUE THREAD

**Issue by super3** [super3/zmine#11]
## [nheqminer-0.5c](https://github.com/nicehash/nheqminer/releases)
- [x] Windows x64
- [ ] Ubuntu_14_04_x64
- [ ] Ubuntu_16_04_x64

## [nheqminer-djezo v0.5a](https://github.com/nanopool/nheqminer-djezo/releases)
- [ ] Linux

## [Genoil](https://github.com/Genoil/ZECMiner/tree/master/releases)
- [ ] Windows

## [EWBF's CUDA Zcash miner v0.3.4b](https://github.com/nanopool/ewbf-miner/releases)
- [ ] Windows 
- [ ] Linux 

## [Excavator v1.1.0a](https://github.com/nanopool/excavator/releases)
- [ ] Windows x64

## Claymore's ZCash AMD GPU Miner v12.6
- [ ] Windows x64
- [ ] Linux

## [bminer-v6.1.0](https://www.bminer.me/releases/)
- [ ] Windows x64
- [ ] Linux

## [dstm's ZCash Cuda miner](https://bitcointalk.org/index.php?topic=2021765.0)
- [ ] Windows x64
- [ ] Linux

**Comment by buxstore** [comment]
EWBF's CUDA Zcash miner v0.3.4b    dstm's ZCash Cuda miner
