### ISSUE TITLE
Build v0.2.1 Release

### ISSUE THREAD

**Issue by super3** [super3/zmine#9]
## Build [nheqminer](https://github.com/nicehash/nheqminer)
- [x] Windows x64
- [ ] Mac
- [x] Linux

## Build zmine
- [x] Windows x64
- [ ] Mac
- [x] Linux

**Comment by super3** [comment]
@montyanderson How should we do our Linux binaries? Nheqminer has ```Ubuntu_14_04_x64``` and ```Ubuntu_16_04_x64``` binaries. Also note "Linux builds will work only on SM5.0 and higher and CPU must have support AVX. CUDA8 required."

**Comment by montyanderson** [comment]
I'm not entirely sure - I'm going to try and compile a version of nheqminer that doesn't require shared libraries, so it should run independently of distro.

**Comment by super3** [comment]
@montyanderson nheqminer Isn't a great miner, so lets skip the Mac release for now.
